import { FC } from "react";
import Image, { StaticImageData } from "next/image";
import image3 from "../assets/images/image3.jpg";
import image4 from "../assets/images/image4.png";
import image5 from "../assets/images/image5.png";
import image6 from "../assets/images/image6.png";
import image7 from "../assets/images/image7.png";
import image8 from "../assets/images/image8.png";

import { styles } from "../styles";
import Dropdown, { DropdownProps } from "../widgets/dropdown";
import NewSection from "../utils/newSection";

const Section4:FC = () => {
  const features: DropdownProps[] = [
    {
      title: "Profitability and Growth",
      description: "At Creon, we handpick cutting-edge AI projects and offer our community and token holders early access and investment opportunities. Our community actively contributes to the growth and profitability of these projects, creating a dynamic ecosystem of innovation and shared success.",
      icon: image5
    },
    {
      title: "Transparent & Fair Decentralized Earnings",
      description: "The key element of our proposal is the continuous access to distributed and decentralized earnings generated by AI tools that we provide through their creation or investment in them. This decentralized structure ensures greater transparency and fairness to all participants in the Creon ecosystem.",
      icon: image6
    },

    {
      title: "Launching the future",
      description: "What's more, Creon is pioneering in offering the first known opportunity to acquire allocations in tokenised AI projects through our Creon Launchpad platform. This gives investors a unique chance for early engagement in the most promising AI projects, opening the door to potentially high returns.",
      icon: image7
    },
    {
      title: "Limitless Possibilities of AI & Crypto",
      description: "The possibilities offered by the integration of AI and cryptocurrencies are limitless, and we're just beginning to explore them. As pioneers, our journey into uncharted territory is fraught with challenges, but the rewards promise to be equally extraordinary. Creon isn’t just about profiting from technological innovation; it's about being part of the process that brings these innovations to life.",
      icon: image8
    }
  ]
    return (
        <NewSection>
                <div className="grid 1000px:grid-cols-3 gap-10 justify-items-center">
                  <div className="1000px:col-span-2">
                    <div >
                        <h2 className={styles.subtitle}>Our vision is to support the innovation of AI blockchain projects <span className="gradient-text">while prioritizing communities and democratizing profits</span></h2>
                        <div className="flex w-full h-full justify-end">
                         <div className="relative">
                         <div className="absolute bottom-0 left-0 w-full h-[14%] bg-gradient-to-t from-[#000000] to-[#00000000]"></div>
                         <div className="absolute bottom-0 left-0 w-[33%] h-full bg-gradient-to-r from-[#000000] to-[#00000000]"></div>
                         <div className="absolute bottom-0 right-0 w-[33%] h-full bg-gradient-to-l from-[#000000] to-[#00000000]"></div>
                         <Image src={image3} alt="CREON" className="" />
                         <Image src={image4} alt="Logo" className="absolute top-[46%] left-[50.2%] w-[13.39%] h-[32%]  transform -translate-x-1/2 -translate-y-1/2"/>
                         <Image src={image4} alt="Logo" className="absolute top-[46%] left-[50.2%] w-[13.39%] h-[32%]  transform -translate-x-1/2 -translate-y-1/2"/>
                         </div>
                        </div>
                    </div>
                  </div>
                  <div className="">
                    {features.map((item:DropdownProps, index) => (
                      <Dropdown key={index} title={item.title} description={item.description} icon={item.icon} />
                    ))}
                  </div>
                </div>
        </NewSection>
    )
};

export default Section4;